### PR TITLE
onFileChange event as param

### PR DESCRIPTION
**Pull request by giolvani**
Passing event as parameter on onFileChange callback, allows me retrieve more data from input file as name, type and size. It makes the export process more dynamic.

Reference about event: http://www.andygup.net/easily-find-image-type-in-javascript/

### CODE REVIEW

**Comment by bharatpatil** [comment]
This is useful

**Comment by bharatpatil** [comment]
This can also be achieved without passing parameter like below in callback:

```javascript
onFileChange: function() {
 if(this.$fileInput.get(0).files) {
	var f = this.$fileInput.get(0).files[0];
	}
}
```

**Comment by giolvani** [comment]
Yeap, you're right!

**Comment by scottcheng** [comment]
Thanks for the PR! This is useful. Merged into dev (ff9f3948763f0ccd8e00dbd0a5ab175013d37201).

**Pull request closed without merging**
